package com.car.show;
import javax.swing.*;
import java.sql.*;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author badsh
 */
public class Stocks extends javax.swing.JFrame {
    Connection connection = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form Stocks
     */
    public Stocks() {
        initComponents();
        showTableData();
    }

    public void showTableData(){
        try {
            connection = MysqlConnect.ConnectDB();
            String Sql = "SELECT * FROM CARS_DETAILS";
            pst = connection.prepareStatement(Sql);
            rs = pst.executeQuery();

            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cname = new javax.swing.JTextField();
        bname = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Invoice = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Brand", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 370, 163));
        getContentPane().add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 141, 80, -1));
        getContentPane().add(bname, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 192, 80, -1));

        jButton1.setText("PURCHASE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Car Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 141, -1, 22));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Brand");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 192, 53, 22));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 93, -1, -1));
        getContentPane().add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 87, 80, -1));

        Invoice.setColumns(20);
        Invoice.setRows(5);
        jScrollPane2.setViewportView(Invoice);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 370, 185));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Price");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 245, -1, -1));
        getContentPane().add(pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 242, 80, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("CARS STOCKS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 120, -1));

        jButton2.setText("INSERT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("E:\\Project\\Database\\Showroom\\src\\com\\car\\show\\bmw_headlights_lights_137326_1920x1080.jpg")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String userName = uname.getText();
        String carName  = cname.getText();
        String brand    = bname.getText();
        String quantity = "1";
        String amount = pname.getText();

        if (carName.isEmpty() || brand.isEmpty() || quantity.isEmpty()) {
            JOptionPane.showMessageDialog(null, "FILL UP THE FORM PROPERLY");
        } else {
            reportRegister(userName,carName,brand,quantity,amount);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String carName  = cname.getText();
        String brand    = bname.getText();
        String amount = pname.getText();

        if ( carName.isEmpty() || brand.isEmpty()) {
            JOptionPane.showMessageDialog(null, "FILL UP THE FORM PROPERLY");
        } else {
            carRegister(carName,brand,amount);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stocks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stocks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stocks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stocks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stocks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Invoice;
    private javax.swing.JTextField bname;
    private javax.swing.JTextField cname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField pname;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables

    private void reportRegister(String userName, String carName, String brand, String quantity, String amount) {
        connection = MysqlConnect.ConnectDB();
        String Sql = "INSERT INTO REPORTS (Name,carname,quantity,amount) VALUES (?,?,?,?)";
        try {
            pst = connection.prepareStatement(Sql);
            pst.setString(1, userName);
            pst.setString(2, carName);
            pst.setString(3, quantity);
            pst.setString(4, amount);

            int rs = pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Reports are saved!");
            Invoice.setText("**************** INVOICE ***************" + "\nCongratulation " +userName+  " For Purchasing\n" + carName + " Brand: " + brand + "\nCar will be Delivered Soon");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void carRegister(String carName, String brand, String amount) {
        connection = MysqlConnect.ConnectDB();
        String Sql = "INSERT INTO CARS_DETAILS (Name,brand,price) VALUES (?,?,?)";
        try {
            pst = connection.prepareStatement(Sql);
            pst.setString(1, carName);
            pst.setString(2, brand);
            pst.setString(3, amount);

            int rs = pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Stock Updated!");
            showTableData();
            // Invoice.setText("**************** INVOICE ***************" + "\nCongratulation " +userName+  " For Purchasing\n" + carName + " Brand: " + brand + "\nCar will be Delivered Soon");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

}
